# Generated by Django 4.0.5 on 2023-04-01 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocha_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='notes',
            new_name='Notes',
        ),
    ]
